server:
  port: 8088

spring:
  jpa:
    hibernate:
      show-sql: true
#      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/db_mess
    username: user
    password: user
  flyway:
    baseline-on-migrate: true
    create-schemas: true
    default-schema: public
    enabled: true
    locations: "classpath:db/migration"
    validate-on-migrate: false

  freemarker:
    expose-request-attributes: true
  mail:
    host: victzeran@mail.ru
    username: Victor Zeransky
    password: 252198718
    port: 465
    protocol: smtps

upload:
  path: /home/victor/Downloads/messenger/uploads

